### PR TITLE
Revert "display totals & exchange rate in usd"

### PR DESCRIPTION
**Pull request by elaineo**
Reverts ethereumproject/emerald-wallet#134
sorry, i accidentally clicked on MERGE. i am an idiot today.

### CODE REVIEW

**Comment by splix** [comment]
do we really need to revert? or maybe keep it merged and fix what wasn't finished in that PR?

**Comment by elaineo** [comment]
@splix sure, that's fine if @whilei does not mind. sorry @whilei :)

**Comment by whilei** [comment]
No problem.
By the way, do either of you  know why I get this error when I try to add a couple modules?
```
// $ npm install -S os-locale locale-currency
// $ npm run build ->
// > Module not found 'child_process', 'fs', and 'spawn-sync'.
// import osLocale from 'os-locale';
// import LocaleCurrency from 'locale-currency';
```
> https://github.com/ethereumproject/emerald-wallet/blob/master/src/lib/types.js#L3

These modules may help with small remaining issue with PR as-is w/r/t currency formatting.

Anyway, shall we go ahead and close this PR? and I'll soon submit a follow-up patch for tidying and fixes

**Comment by splix** [comment]
I don't think `os-locale` `locale-currency` will work in browser, it seems to be node.js backend libraries

**Comment by whilei** [comment]
Copy that.

Closing...

**Pull request closed without merging**
