### PR TITLE
app executables should use appUserData/bin path

### PR DESCRIPTION
**Pull request by whilei**
@splix This is what I used to get it running for me. I guess we'd rather use an Electron/bin path to keep the executables, though?

### CODE REVIEW

**Comment by splix** [comment]
It's better to use app dir provide by Electron: https://electron.atom.io/docs/api/app/#appgetpathname

We store configs here currently, and binaries should be under that dir too

**Comment by whilei** [comment]
Roger that, see latest changes.

**Comment by splix** [comment]
@whilei I've actually fixed the dir with last update to PR #155

**Comment by whilei** [comment]
OK, I will rebase/merge your changes first thing in the morning.

**Comment by whilei** [comment]
Closing in lieu of #160

**Pull request closed without merging**
