### PR TITLE
Front/backend communication refactoring

### PR DESCRIPTION
**Pull request by gagarin55**

### CODE REVIEW

**Comment by whilei** [comment]
👍  just a sidenote -- in case you want to be "conventional," I typically use the `[WIP]` prefix to denote "work-in-progress" PR's, like [this one](https://github.com/ethereumproject/go-ethereum/pull/328)

**Comment by whilei** [comment]
I don't know if you're still working on it, but have tried 2715372 and still getting https://github.com/ethereumproject/emerald-wallet/issues/311

**Comment by r8d8** [comment]
2017-08-19-074334_1600x900_scrot
can't send transaction with ledger

**Comment by gagarin55** [comment]
Let's merge it and continue development

**Pull request merged**
