### PR TITLE
Download and run Geth

### PR DESCRIPTION
**Pull request by splix**
Electron App will download, verify PGP signature, upzip and run Geth. Then use it directly, not through Connector

### CODE REVIEW

**Comment by splix** [comment]
fix #122

**Comment by elaineo** [comment]
Does package work right now?
screen shot 2017-06-15 at 7 59 59 pm

**Comment by splix** [comment]
should work, did you do `npm install`?

**Comment by elaineo** [comment]
@splix yeah, i did... the electron package releases all worked before this branch. i will spend some time trying to see what's wrong on my machine. the regular build works and the code looks ok.

**Comment by elaineo** [comment]
So, this part is not properly importing `fs`, I think

```Javascript

/***/ }),
/* 18 */
/***/ (function(module, exports, __webpack_require__) {

// Monkey-patching the fs module.
// It's ugly, but there is simply no other way to do this.
var fs = module.exports = __webpack_require__(140)
```

**Pull request merged**
