### PR TITLE
i18n: init using react-i18next

### PR DESCRIPTION
**Pull request by sorpaas**
This adds an i18n framework using react-i18next. Using this by:

1. `import { translate } from 'react-i18next';`
2. Wrap the component using `translate("category")(...)` and use `t("name", { ...options })` for texts to be translated.
3. Add the required translation `name` in `locales/lang/category.json`.

### CODE REVIEW

**Comment by sorpaas** [comment]
@dulanov How will this PR be dealt with? Seems right now we've got conflicts. Should I push this at a later time or it is possible to start translation now?

**Comment by dulanov** [comment]
Always resolve conflicts firstly, @elaineo answer please, is it ok to merge it now?

**Comment by elaineo** [comment]
Ah! Is this a followup to the discussion on slack about adding language support? Everything looks fine to me, but I assume this will be a work in progress, right?

**Comment by sorpaas** [comment]
I've got the framework in. It's working. 😂  So in my opinion it's okay to merge. After that we can gradually replace hard-coded texts with `t(...)` and add translations.

I'll resolve the conflicts now.

**Pull request merged**
