### PR TITLE
Elaine/import account

### PR DESCRIPTION
**Pull request by elaineo**
Imports file, sends file and password to connector. Issue #5 
Let me know if it should decrypt file on client side, and only forward decrypted data.

### CODE REVIEW

**Comment by splix** [comment]
@elaineo It seems that you forgot to commit updated `package.json`

**Comment by splix** [comment]
ok :)

**Comment by dulanov** [comment]
@elaineo password not needed for import, only during a transaction

**Comment by dulanov** [comment]
@elaineo we want to implement all account logic in connector securely, and to relieve the UI side from this stuff.

**Comment by elaineo** [comment]
@dulanov ok thanks, i will remove the password field

**Comment by pascaldekloe** [comment]
Too bad. I kind of like the idea that the data leaves the JS VM secured. Especially if the code is intended to be used as a library by 3rd parties. Android Apps come to mind.

**Comment by dulanov** [comment]
@pascaldekloe what's too bad again please, we exactly want to extract all the account / wallet / contacts stuff require security and performance benchmarks in a separate library implemented by Rust, why do you think it's a bad idea?

**Comment by splix** [comment]
I don't see much conflict here. JS can make encryption/tx sign too, but a default implementation will delegate it to connector. Because it's easier to store persistent data such as keys here, rather than in browser's webstorage. 
Connector RPC API can accept signed transaction as well, if someone will decide to sign them on JS side

**Comment by dulanov** [comment]
@pascaldekloe this is no problem, dApp can sign trinsactions itself

**Pull request merged**
