### PR TITLE
electron,build,configs: Create distribution-ready packaging

### PR DESCRIPTION
**Pull request by whilei**
Should create a distributable electron application built for win, linux, and mac. Rel #141 

- __Note:__ Rename `content_base` from `/build` -> `/app` (you'll want to `rm -rf` your git-ignored dir `/build`... `npm run start/build` will automatically rebuild you the new one (`/app`) and serve from that if you're developing)
- Create dir `/build` containing images and icons specific for `electron-builder`
- Add `"build"` configuration to `package.json`

Currently...
- Builds succeed, except for my system (OSX) throwing an error requiring Wine when building for windows.
- Running the app as built by `electron-builder` results in `window` not found error... I think this may be due to lack of integration with the `electron-package` scripts.

----
TODO 
- [x] integrate with `electron-packager` <-- swapped for `electron-builder`
- [x] ~~sign with an official ETCDEV signature instead of my ~~ <-- functionality pushed to later feature
```
Signing app (identity: 34DCCEF7F961A3C83C31856326E1C4267BB36A84 Developer ID Application: Rotblauer, LLC (3T8C45E2VR))
```
- [x] include http://isaacardis.com/z/emerald-wallet/icon.ico at https://github.com/ethereumclassic/Media_Kit instead (apparently windows wants its icons from a url for auto-upgrading capability)
  + configuration at https://github.com/whilei/emerald-wallet/blob/e953a295727ae1f5314e097e275f7150f80abf30/package.json#L142

### CODE REVIEW

**Comment by splix** [comment]
Do we need all this icons to put as sources? especially as ZIP files. Also it's unclear which license is used for this images. Can't we download them as dependencies during the build?

**Comment by whilei** [comment]
The images under `src/images/` (except for the logo, of course) are unnecessary --  I had just left them in there for reproducability.

The icons under `/build/`:
```
-rw-r--r-- 1 ia staff 6.7K Jun 20 12:36 background.png
-rw-r--r-- 1 ia staff 113K Jun 20 12:34 icon.icns
-rw-r--r-- 1 ia staff 362K Jun 20 12:34 icon.ico
```

are necessary for `electron-build` as far as I know
- http://electron.rocks/electron-builder-explained/
- https://github.com/electron-userland/electron-builder/wiki/Optionshttp://electron.rocks/electron-builder-explained/
  > Resources need to be in this folder by these names, since electron-builder is expecting them.

**Comment by whilei** [comment]
@splix @elaineo just an FYI update: building and packaging are still, for me, roadblocked by #154 

If anybody's got a big idea about it I'd love to hear it. Google's been listening to me complain all afternoon.

**Comment by whilei** [comment]
Just rebased on master and with @splix's [edits](https://github.com/whilei/emerald-wallet/pull/2/commits/8d0971d9b121a527bfad118cca4ba411181b38bc).

ae9ef30 swaps `unzip2` package for `extract-zip` package because the latter has no dependency on `fs`, which [may interfere with electron's `fs`](https://github.com/ethereumproject/emerald-wallet/issues/154).

Unfortunately, I'm still getting:
```
$ npm run package
open releases/EmeraldWallet.app
```
screen shot 2017-06-23 at 09 03 42

**Comment by whilei** [comment]
able to get a different error:

screen shot 2017-06-23 at 11 55 58

**Comment by splix** [comment]
it seems that code wasn't compiled to plain js (or you have to enabled babel, not sure how it works in Electron runner)

**Comment by whilei** [comment]
see last couple commits for a new approach to try moving `/electron/*` to `/src/` to ensure they all get webpacked during `node build`. seems to almost work except for strange new error message which you'll find in the commit message bodies

**Comment by whilei** [comment]
a07d4fc works, woohoo! Still todo: 
- [ ] refine npm scripts
- [ ] remove/replace `electron/package.js` with electron-builder programmatic api
- [ ] bundle with emerald (...?)

**Comment by whilei** [comment]
Be advised!: I'm going to use the `--force` to push a squashed and up-to-date branch. Brace yourselves.

A mostly-complete record of the individual commits can be found on my fork on branch [builder-publisher](https://github.com/whilei/emerald-wallet/tree/builder-publisher).

**Comment by splix** [comment]
we need to compile and package connector also

`cargo install emerald-cli -v 0.9.0` then copy into bin

**Comment by dulanov** [comment]
`crate install --vers 0.9.0`, we will publish it in half hour.

**Comment by whilei** [comment]
@splix @dulanov Better to download the latest release (like geth) than `cargo install` since that requires the system to have cargo set up?

**Comment by dulanov** [comment]
It's just one command indeed - `curl https://sh.rustup.rs -sSf | sh`

**Comment by dulanov** [comment]
But we will set up also github releases, so you can download from github binary assets directly.

**Comment by whilei** [comment]
Is the download possible to do today, or should we use `cargo install` for the time being and plan on phasing that out once the releases are up and running later?

**Comment by dulanov** [comment]
Start from `cargo install` and I ask help for @bunda to prepare github releases for you. But one more - it's not good way to distribute something from github releases, IMHO.

**Comment by whilei** [comment]
Do you think it's better to use a download from different release source like Bintray, or is it the general downloading that's the issue?

**Comment by dulanov** [comment]
@ia Another problem, we will probably split current `emerald` into several other tools, you whant to download all of them directly from github in binary form instead of using standard Rust package system?

**Comment by whilei** [comment]
I didn't know that... not necessarily, I'm just aiming for the most sustainable and easy-for-the-user option. If you think `cargo` is the way to go then I think we should do that.

**Comment by whilei** [comment]
Replaced by #190, closing.

**Pull request closed without merging**
